### ISSUE TITLE
Product Hunt feed does not refresh.

### ISSUE THREAD

**Issue by ozgn** [karakanb/devo#100]
Thank you for this lovely extension. 🍻
I think there is a small issue with the Product Hunt feed. The Product Hunt feed has been showing the feed of the 5th of April since 2 days. There is no any change when I refresh it.

**Comment by erikfiala** [comment]
Any update on this? I'm kinda tired of seeing old PH projects on my Devo feed 😆

**Comment by Ahacad** [comment]
sadly still not working now 😭

**Comment by Mheaus** [comment]
Hey, I've added my own endpoints for my copy of your project.
The data received has changed a little from your original payload but if you want, you can use them.

https://www.adbrt.com/api/github
https://www.adbrt.com/api/hackernews

**Comment by karakanb** [comment]
I am doing alright with the backends I manage for now for HN and GitHub, thanks a lot for offering though.

I am closing this issue now, feel free to comment / upvote the PH issue to bring more visibility: https://github.com/producthunt/producthunt-api/issues/292

I'll fix Devo if the PH team fixes their API, otherwise there's nothing I can do.
