### ISSUE TITLE
Product Hunt Broken

### ISSUE THREAD

**Issue by hipstersmoothie** [karakanb/devo#12]
<img width="787" alt="screen shot 2018-10-07 at 10 54 07 pm" src="https://user-images.githubusercontent.com/1192452/46593854-09942e00-ca84-11e8-9084-dde06d4bca9e.png">

<img width="1075" alt="screen shot 2018-10-07 at 10 54 25 pm" src="https://user-images.githubusercontent.com/1192452/46593859-0d27b500-ca84-11e8-8854-60165beee0d0.png">

**Comment by karakanb** [comment]
Hey! I think there was something wrong with the Product Hunt API, as their mobile applications were also down because of the same error, ` Unexpected token < in JSON at position 0 at JSON.parse`. The application service that provides Product Hunt data is basically a wrapper over the public PH API; so, my hands were tied there, and it seems to be resolved now.

**Comment by karakanb** [comment]
Oh, this seems to be my mistake. Even though I had seen the same error on their mobile application, the problem we have here is not the same, it seems like we have exceeded the rate limits, will investigate it.

```json
{
    "error": "rate_limit_reached",
    "error_description": "Sorry. You have exceeded the API rate limit, please try again later.",
    "details": {
        "limit": 25,
        "remaining": 0,
        "reset_in": 156
    }
}
```

**Comment by hipstersmoothie** [comment]
I'll close this as it's not really an issues with you
