### ISSUE TITLE
Will be great to see an option for adding more windows into the grid (:

### ISSUE THREAD

**Issue by obiwankenoobi** [karakanb/devo#26]
Hey! First of all, thank you for the tool! I love it and it makes my morning coffee in the office way better! 

One thing I just discovered is that you can change each feed to another feed - which is great and it make me think about adding more windows to support more feeds! Is that something you working on, or maybe you will be open for PR for this kind of feature? Let me know! (:

**Comment by karakanb** [comment]
Hey there! Thanks for the kind words, I am glad to hear that it makes your day slightly better. 🎉  

That was something I looked into a while ago, I wanted to be able to drag and drop the windows on a snapped grid, and adding/removing windows would be possible, but unfortunately, I couldn't find an easy way of doing it at the time. I have been thinking about doing it in an easier way, having a certain set of layouts instead of drag/drop which should be easier; however, I also don't know if it would be worth the effort since it seems like having 4+ windows might be very distracting and you are the first person to ask this apart from myself. 🙂 

I am open to PRs on this, and I am also open to discussing how to implement this as well. Let me know if you have any ideas on it, it would be good aligning on this before any of us starts working on it.

**Comment by karakanb** [comment]
I have merged a different version of this with a set of pre-defined layouts, here are the examples if you are interested: https://github.com/karakanb/devo/pull/51 

I'll be releasing this in the upcoming days hopefully, therefore I consider this issue done as well.
