### ISSUE TITLE
Disable autoplay for producthunt gifs

### ISSUE THREAD

**Issue by ForsakenHarmony** [karakanb/devo#32]
Would be nice to have an option to disable autoplay / maybe only on hover

**Comment by karakanb** [comment]
Hey, thanks for the feedback. I don't think this is easily doable at the moment since all these images are coming as GIFs from Product Hunt API. I did a quick search, seems like there are some JS-based solutions but I don't think this would be an easily doable thing. Would you be open to submit a PR for this behind a feature toggle?

**Comment by karakanb** [comment]
I am closing this issue as I don't plan on spending time on it at the moment, feel free to reopen in case you see an opportunity for it.
