### ISSUE TITLE
Add support for Lobsters on burakkarakan.com/devo/

### ISSUE THREAD

**Issue by quyleanh** [karakanb/devo#52]
The website currently has no option for Lobsters.
Could you add it?

**Comment by karakanb** [comment]
Hey, unfortunately I don't think it is possible since the Lobsters API does not have the proper CORS headers, making it impossible to send cross-origin requests to their API. The platform works all good in the extension, so you might want to think about installing the extension rather than visiting the website for the content, especially since the website is not getting updated even though the extension is quite regularly updated. 

I'll be closing this issue since there is no solution that I can do to make Lobsters work on the webpage, it is all on their side.
