### ISSUE TITLE
API seems to be erroring, no content will load

### ISSUE THREAD

**Issue by NileDaley** [karakanb/devo#60]
It looks like requests to the API (https://devo.ams3.digitaloceanspaces.com/) seem to be erroring, leading to no content loading. Strange thought that it still works on burakkarakan.com/devo.

I've tried on Firefox and Chrome and still see the same issue.

 
![Screenshot 2021-02-05 at 10 24 44](https://user-images.githubusercontent.com/15862011/107021682-5eebc180-679c-11eb-9361-69303c10f144.png)

**Comment by karakanb** [comment]
Hey, thanks for the report. Are you still having the issue? I don't know what went wrong, but it seems to be working for me now, and we can investigate further if you are still having trouble.

The reason burakkarakan.com/devo works is because they are using different backend APIs, which reminds me to update burakkarakan.com/devo one as well to point at DigitalOcean.

**Comment by NileDaley** [comment]
Sorry @karakanb, I missed your reply. All seems to be working now, thanks for sorting 👍
