### ISSUE TITLE
Github Trending, Product Hunt and Hacker News have problems 

### ISSUE THREAD

**Issue by etolbakov** [karakanb/devo#62]
Hell @karakanb 
thanks for this add-on! It is really useful!

Today I found some wierd behavoir with the tabs, Please find the screenshot below:

<img width="1458" alt="Screenshot 2021-02-11 at 09 52 56" src="https://user-images.githubusercontent.com/3762201/107622042-268e2c80-6c4f-11eb-8c17-0c787b341781.png">
"Dev Community" and "Designer News" are loading fine, so the problem is only with "Github Trending", "Product Hunt" and "Hacker News"

---
Regards, Eugene

**Comment by karakanb** [comment]
Hey, this is exactly the behavior I had intended to. 🙂 

I put that message in those cards, because you are currently on an old version of Devo, and you need to manually upgrade. I tried to be as clear as possible in the messages there, so if you'd like to continue using the tool you'll need to upgrade manually. Please go to the extensions page of your browser, and click "Update" there, and give the permissions if it asks for any. An alternative would be to uninstall and re-install the extension if you cannot update.

I'll be closing this issue since the API will stop working soon and it has been more than 3 months at this point since this API is deprecated and we are moving to the new backend. Let me know if you are having issues with the newer versions.
