### ISSUE TITLE
Grid views not working

### ISSUE THREAD

**Issue by erikfiala** [karakanb/devo#69]
Hey! Thanks for the great work with this extension. I love it :) 

Just stumbled upon a small bug - changing grid views is not working for me, showing everything in a Single Column view.

**Comment by karakanb** [comment]
Hey, I'd need more information in order to be able to debug this, and I'd need to use your debugging skills as well.
- What is the browser + version?
- What is the Devo version?
- Are there any logs on the console?
- Have you tried uninstalling and reinstalling Devo?

Let me know about the answers to these so that we can debug and fix the issue. 🙂

**Comment by erikfiala** [comment]
- Chrome Version 93.0.4577.82 (Official Build) (arm64)
- Devo 1.9.3
- No logs in the console
- Haven't tried. Will let you know after I do that 🙂

**Comment by erikfiala** [comment]
Hey, I just found out the issue and it wasn't technical at all!

This is so silly, but my page was zoomed in 125%, and every time I opened a new tab, it just stayed zoomed-in. 😂

I'm closing the issue now. 😮‍💨

**Comment by karakanb** [comment]
oh, I see, I didn't think about it at all 😂 glad to hear it is resolved!
