### ISSUE TITLE
Follow system theme feature

### ISSUE THREAD

**Issue by theedoran** [karakanb/devo#75]
First of all, I have to say that I really love this extension and can't live without it now.
Now, talking about the "problem": I'd love to see a "follow system theme" auto-switch in the extension. I like to keep my OS (macOS) in automatic theme mode, and while many applications and websites auto-switch from light to dark mode (and viceversa), Devo keeps the previously selected option. It isn't a big deal, obviously, but it would be nice if we could have this new option implemented, maybe with a three way switch or a simple checkbox.

**Comment by karakanb** [comment]
hey, thanks for the comment. I believe we are respecting that when the theme is setup for the first time, but if the user toggles it then we pick the toggle as a default. Introducing yet another way of managing that might be tricky, given that we have no current way of having configuration for Devo in order to keep it simple. If you have ideas about where could it live, or if you'd like to prepare a PoC, I'd take a look at it. I'll keep this in mind as well in case I can think of a simple and elegant way.

**Comment by theedoran** [comment]
Ok, thanks for the information. I'll try to work on it and make a PR in the next days, If I find the time, hopefully. Closing for now.
